site_name: My Study Notes
site_url: https://jhao1122.github.io/Notes/ 

theme:
  name: material
  features:
    - navigation.tabs  
    - navigation.sections 
    - navigation.top 
    - search.suggest 
    - content.code.copy 
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        title: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        title: 切换到浅色模式
  language: zh 

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true